name: Nightly Build

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r setup/requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          BUILD_ARGS=""
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            BUILD_ARGS="--target-architecture universal2"
          fi
          pyinstaller --onefile --windowed --name "ImageCompare" ${BUILD_ARGS} app/image_compare_pyqt.py

      - name: Generate timestamp
        id: timestamp
        run: |
          echo "BUILD_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Rename executable
        id: rename
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            BINARY_NAME=ImageCompare-nightly-${{ steps.timestamp.outputs.BUILD_DATE }}.app
            mv dist/ImageCompare.app dist/${BINARY_NAME}
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            BINARY_NAME=ImageCompare-nightly-${{ steps.timestamp.outputs.BUILD_DATE }}
            mv dist/ImageCompare dist/${BINARY_NAME}
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            BINARY_NAME=ImageCompare-nightly-${{ steps.timestamp.outputs.BUILD_DATE }}.exe
            mv dist/ImageCompare.exe dist/${BINARY_NAME}
          fi
          echo "BINARY_NAME=${BINARY_NAME}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.rename.outputs.BINARY_NAME }}
          path: dist/${{ steps.rename.outputs.BINARY_NAME }}
